name: Diceware.cat
description: "Diceware en Català: Contrasenyes fàcils de recordar!"
author: "Toni Homedes i Saun"

highlighter: pygments
github: [Repository metadata]
markdown: redcarpet
pygments: true
baseurl: /
