#! /usr/bin/env python

import random

random.seed()

with open("paraules.txt", "rt") as f: paraules = f.read().splitlines()

print
for n in range(4, 13):
    l = []
    for i in range(n):
        l.append(paraules[random.randint(0, 7775)])
    print "%-2d: %s" % (n, " ".join(l))
print

